### ISSUE TITLE
support for package@x.x.x-beta.x

### ISSUE THREAD

**Issue by qighliu29** [nathanhleung/install-peerdeps#12]
it failed to parse the package name when executing `install-peerdeps bootstrap@4.0.0-beta` and got the error:
`C:\Users\Administrator\AppData\Roaming\npm\node_modules\install-peerdeps\lib\cli.js:86`
     `packageName = parsed[1];`

**Comment by nathanhleung** [comment]
Thanks for sending this issue - can you paste the output from the Terminal after running the command?

**Comment by nathanhleung** [comment]
[v1.4.0](https://github.com/nathanhleung/install-peerdeps/releases/tag/v1.4.0) fixes this. Thanks for the issue.
