### ISSUE TITLE
option to not require permission to install on yarn.

### ISSUE THREAD

**Issue by tnrich** [nathanhleung/install-peerdeps#13]
Hey there,

My post install script is getting hung up and not finishing:

![image](https://user-images.githubusercontent.com/2730609/31516668-57904cb2-af67-11e7-86f9-85094e1da4da.png)

I think if there were an option to auto-install if yarn is detected that would fix the issue for me. Thanks!

**Comment by nathanhleung** [comment]
Hi, to install with Yarn automatically just use the `--yarn` flag, or its shorthand alias `-Y`:

```
Usage: install-peerdeps <package>[@<version>], default version is 'latest'

Installs the specified package along with correct peerDeps.

Options:
 
  -h, --help        output usage information
  -V, --version     output the version number
  -d, --dev         Install the package as a devDependency
  -o, --only-peers  Install only peerDependencies of the package
  -S, --silent      If using npm, don't save in package.json
  -Y, --yarn        Install with yarn
```
