### ISSUE TITLE
Do we have the actual source code for this tool?

### ISSUE THREAD

**Issue by ctjlewis** [nathanhleung/install-peerdeps#141]
I'm sure this isn't news to anyone who maintains this, but I've never seen a repo with Babel output *as* the source:

```javascript
// test/cli.test.js
var _child_process = require("child_process");

var _fs = _interopRequireDefault(require("fs"));

var _path = _interopRequireDefault(require("path"));

var _tape = _interopRequireDefault(require("tape"));

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }
...
(0, _tape.default)("adds an explicit `--no-save` when using `--silent` with NPM", async t => {
  t.plan(1);

  try {
    const command = await getCliInstallCommand(["eslint-config-airbnb", "--silent"]);
    t.equal(/\s--no-save\b/.test(command), true);
  } catch (err) {
    t.fail(err);
  }
});
```

Does... the original source exist anywhere? I was going to work on a PR for #140 but this is not very workable at all.

**Comment by ljharb** [comment]
Every single package on npm that uses a transpiler has the input in git, and the output exists *nowhere* but in npm.

You clone the repo, run `npm install`, and run `npm run build` to build it - again, like virtually every single project that uses a transpiler.

What exactly is your question? This file exists here: https://github.com/nathanhleung/install-peerdeps/blob/master/src/cli.test.js

**Comment by ctjlewis** [comment]
Yes - what was odd about this project is it is transpiling source and putting the output in `test/`, where I was expecting test source to be. I see now the pipeline is weirdly `src/ -> test/`, rather than `src/ -> dist/` or something clearer.

**Comment by ljharb** [comment]
The output directory is never something to assume - it's always a convention, and you always have to check the config to see where things end up.
