### ISSUE TITLE
Use of .npmrc config

### ISSUE THREAD

**Issue by IAfanasov** [nathanhleung/install-peerdeps#16]
Use .npmrc file to get the registry url

I have a private registry and then I run 
`install-peerdeps valhalla-engine-test`

I get en error
`ERR That package doesn't exist. Please try another.`

That because global npm server is used instead of one that setup in .npmrc file

**Comment by nathanhleung** [comment]
Can you attach your personal .npmrc file so I can take a look at your config?

**Comment by IAfanasov** [comment]
I'm not comfortable with public access to it. Sent you it in email to @gmail.com

**Comment by nathanhleung** [comment]
[v1.4.0](https://github.com/nathanhleung/install-peerdeps/releases/tag/v1.4.0) adds a `--registry` option which allows you to specify a registry. Please try it out and let me know if you have any further issues.

**Comment by IAfanasov** [comment]
Only 2 months passed and I'm again working on this task (:

It worked but took me time to figure out that `https://npm.mydomain.com/` is not working and last slash should be removed. So the registry string should be `https://npm.mydomain.com`.

**Comment by nathanhleung** [comment]
Thanks - I added a note to the [README](https://github.com/nathanhleung/install-peerdeps#installing-from-a-custom-registry) about not including the trailing slash

**Comment by IAfanasov** [comment]
@nathanhleung as a one of the ux tules says: better prevent user opportunity to make error rather then make good error message. so, it would be definitely better to make it work with and without trailing slash

**Comment by nathanhleung** [comment]
Fixed in a57d4f5. Thanks again for the idea.
