### ISSUE TITLE
regex that checks package name fails if there is a .

### ISSUE THREAD

**Issue by brucewpaul** [nathanhleung/install-peerdeps#17]
When using `enzyme-adapter-react-15.4`, the `.` is causing an error in the regex. Changing the regex to the following at least solved this: `/^@?([\/\w\.-]+)(@([\d\w\.-]+))?$/`

Although, there are additionally concerns in terms of packages names that will continue to break the regex such as scoped packages.

**Comment by brucewpaul** [comment]
I see now that the tests account for scoped packages (@angular), so nevermind that

**Comment by nathanhleung** [comment]
fixed in #18
