### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by corysimmons** [nathanhleung/install-peerdeps#19]
![image](https://user-images.githubusercontent.com/224636/34189227-8e32e64a-e508-11e7-9561-b14f541224ef.png)

😪

**Comment by nathanhleung** [comment]
It looks like babel-preset-env doesn't have peerdeps until the beta releases - the current release does not have peerdeps.

See current [package.json](https://github.com/babel/babel-preset-env/blob/master/package.json) and beta [package.json](https://github.com/babel/babel/blob/master/packages/babel-preset-env/package.json).

Can you try running `install-peerdeps babel-preset-env@7.0.0-beta.35`?

**Comment by corysimmons** [comment]
What are all these warnings then?

![image](https://user-images.githubusercontent.com/224636/34240058-8d5d45f4-e5d9-11e7-8a9c-0f747f7feca7.png)

**Comment by nathanhleung** [comment]
Can you attach your package.json?

**Comment by corysimmons** [comment]
tbh no, I deleted the project and moved onto something else.

**Comment by nathanhleung** [comment]
Ok - I'm still interested in fixing this issue, though, so let me know if you see this problem again.
