### ISSUE TITLE
Installed not all dependencies and version string are different

### ISSUE THREAD

**Issue by IAfanasov** [nathanhleung/install-peerdeps#20]
I made a package with peer deps

```json
"peerDependencies": {
	"@angular/animations": "4.3.6",
	"@angular/common": "4.3.6",
	"@angular/compiler": "4.3.6",
	"@angular/core": "4.3.6",
	"@angular/forms": "4.3.6",
	"@angular/http": "4.3.6",
	"@angular/platform-browser": "4.3.6",
	"@angular/platform-browser-dynamic": "4.3.6",
	"@angular/router": "4.3.6",
	"@progress/kendo-angular-dateinputs": "1.0.6",
	"@progress/kendo-angular-intl": "1.2.2",
	"@progress/kendo-angular-l10n": "1.0.4",
	"@telerik/kendo-intl": "1.2.0",
	"classlist.js": "1.1.20150312",
	"rxjs": "5.4.3"
}
```

I made a consumer project with only 2 deps:

```json
"dependencies": {
	"@angular/animations": "4.4.1",
	"@valhalla/engine-test": "0.0.7"
},
"devDependencies": {
	"install-peerdeps": "1.4.1"
}
```

I run 
`node ./node_modules/install-peerdeps/lib/cli valhalla-engine-test -r https://npm.1forma.ru`

And after it package.json of consumer contains:

```json
"dependencies": {
	"@angular/animations": "4.4.1",
	"@progress/kendo-angular-dateinputs": "^1.0.6",
	"@progress/kendo-angular-intl": "^1.3.0",
	"@progress/kendo-angular-l10n": "^1.0.5",
	"@telerik/kendo-intl": "^1.2.0",
	"@valhalla/engine-test": "0.0.7",
	"classlist.js": "^1.1.20150312",
	"valhalla-engine-test": "0.0.2"
},
"devDependencies": {
	"install-peerdeps": "^1.4.1"
}
```

And the issue:
1. not all peer dependencies are installed but there is no warnings about it, that is tolerable. Anyway, I prefer to have all deps listed.

2. version strings are different from original project
original
`"@progress/kendo-angular-l10n": "1.0.4",`
set by install-peerdeps
`"@progress/kendo-angular-l10n": "^1.0.5"`
next operation with peer npm throws warning
`npm WARN @valhalla/engine-test@0.0.7 requires a peer of @progress/kendo-angular-l10n@1.0.4 but none was installed.`

3. Have no idea why `"valhalla-engine-test": "0.0.2"` appeared. Not sure is it my fault or not

**Comment by nathanhleung** [comment]
Sorry for getting to this issue so late. I can answer one of your questions right now but I'm still working on the other two.

For question 1, not sure what's happening. I'll look into it.

For question 2, I changed the version parsing mechanism in 1.5.0. Let me know if it helps.

For question 3, you need to run `install-peerdeps` with the `--only-peers` flag, or else the package itself will also be installed.

**Comment by nathanhleung** [comment]
Closing in favor of #43 (install-peerdeps overwrites existing module)
