### ISSUE TITLE
Breaks on older node

### ISSUE THREAD

**Issue by ljharb** [nathanhleung/install-peerdeps#21]
https://github.com/nathanhleung/install-peerdeps/blob/master/.babelrc#L5 targets node 4; could this be changed to target an earlier version, like 0.10 or 0.8?

**Comment by nathanhleung** [comment]
I can look into it. What's the earliest version you need?

**Comment by ljharb** [comment]
For airbnb/prop-types, 0.10 would suffice. Thanks!

**Comment by nathanhleung** [comment]
Just pushed a new release targeting Node v0.10! Let me know if it's working on your end and I can close this issue.

**Comment by ljharb** [comment]
Thanks! Looks like `has-yarn` also has a similar issue, but this one's all set :-)
