### ISSUE TITLE
Cannot install package that is part of a private organization

### ISSUE THREAD

**Issue by bytheway875** [nathanhleung/install-peerdeps#22]
When attempting to install a package that is part of an npm organization @my-organization/package-name, I'm getting an error that says:

`ERR That package doesn't exist. Did you mean to specify a custom registry?`

Even after specifying the registry, I get the error. 

Wondering if this might have something to do with the way that the package name gets encoded?

---- 

Edited To Add: Hmm... the problem may not be with the organization because i was able to use this for `@angular/core` just fine...

**Comment by bytheway875** [comment]
Wondering if it might be because it is a private package and need an auth token?

**Comment by bytheway875** [comment]
I created a PR to address and resolve this issue by allowing users to pass their npm token as a header: 

https://github.com/nathanhleung/install-peerdeps/pull/23

**Comment by nathanhleung** [comment]
Closed in #23
