### ISSUE TITLE
Support proxy envs

### ISSUE THREAD

**Issue by ibigpapa** [nathanhleung/install-peerdeps#3]
i've got http, https, and ftp proxy envs set both in caps and lower and this times out.

**Comment by ibigpapa** [comment]
http://stackoverflow.com/questions/3862813/how-can-i-use-an-http-proxy-with-node-js-http-client

Found that which looks like all that's left is to wire up the logic of insspecting environment vars

**Comment by nathanhleung** [comment]
Hi! Do you want to submit a pull for this?

**Comment by Zamiell** [comment]
I too have recently found that this program does not obey `HTTP_PROXY` / `HTTPS_PROXY` environment variables, which is quite frustrating. @nathanhleung this would be a welcome addition.

**Comment by nathanhleung** [comment]
@Zamiell Thank you for your comment. I've never used proxy environments, however, so I'm not exactly sure how to solve this issue.

Could you tell me how I could set up an environment similar to yours (i.e. with proxies) so I can develop a fix?

**Comment by Zamiell** [comment]
From Ubuntu 16.04, for example:

```
james@ubuntu:~$ curl http://checkip.dyndns.org/
<html><head><title>Current IP Check</title></head><body>Current IP Address: 72.70.46.190</body></html>
james@ubuntu:~$ export http_proxy=http://52.25.73.81:80/
james@ubuntu:~$ curl http://checkip.dyndns.org/
<html><head><title>Current IP Check</title></head><body>Current IP Address: 52.25.73.81</body></html>
```
So the curl program is checking for the existence of this environment variable at runtime, and then if it is present, it uses it. Generally speaking, the `HTTP_PROXY`, `HTTPS_PROXY`, `http_proxy`, and `https_proxy` variables are typically the ones obeyed by command line software. Here's an excellent StackExchange thread that goes into more detail: https://unix.stackexchange.com/questions/212894/whats-the-right-format-for-the-http-proxy-environment-variable-caps-or-no-ca

**Comment by nathanhleung** [comment]
@ibigpapa @Zamiell newest release v1.4.0 should fix this - please test and let me know if you have any problems.

**Comment by Zamiell** [comment]
I tested it out and it doesn't seem to work:
```
install-peerdeps --dev eslint-config-airbnb-base
install-peerdeps v1.4.0
ERR Error: tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:80
```
Maybe @ibigpapa can weigh in?

**Comment by nathanhleung** [comment]
Could you try running it with the variable in the same command? e.g. `HTTPS_PROXY=https://my.proxy.com:1000/ install-peerdeps --dev eslint-config-airbnb-base`

**Comment by Zamiell** [comment]
I'm on Windows, so what you posted won't work.

```
C:\Users\Zamiell\Repositories\test-repo>set HTTPS_PROXY="http://myproxy.com:80" && install-peerdeps --dev eslint-config-airbnb-base
install-peerdeps v1.4.1
ERR Error: tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:80
```

Any tips?

**Comment by nathanhleung** [comment]
@Zamiell Thanks for your patience - the newest released version has a `--proxy` flag which you can pass an explicit proxy to.

**Comment by Zamiell** [comment]
Thank you @nathanhleung !
