### ISSUE TITLE
Global support (npm)

### ISSUE THREAD

**Issue by gwicksted** [nathanhleung/install-peerdeps#37]
Would be great to have global install support.  Alternatively (less preferable), install-peerdeps should not proceed when passed a global flag (since it won't do what you expect).

`install-peerdeps tslint -g`

results in an:

`npm install tslint@5.11.0 typescript@>=2.9.0-dev --save`

when it should perform:

`npm install tslint@5.11.0 typescript@>=2.9.0-dev -g`

otherwise the following behavior occurs (on a non-npm project directory):

1) you get a warning about a package.json not existing followed by warnings about required fields missing from this file
2) npm creates a package-lock.json file in the current directory and suggests you commit it
3) packages get installed to a new node_modules directory

worse is what happens on a project directory:

1) it saves this new requirement to the runtime dependencies of your existing package.json
2) packages get installed to your local node_modules directory

**Comment by gwicksted** [comment]
Submitted PR #38 to add support for this feature

**Comment by gwicksted** [comment]
Tests in PR #38 appear to be failing in certain older versions of node.  I did notice this in the tape repo regarding the particular error logged by travis: https://github.com/substack/tape/issues/160 where it is summed up as "tl;dr: all test cases must be synchronously declared." yet `async function getCliInstallCommand(extraArgs) ` is not synchronous.  Could probably switch to `spawnSync` to remove the async requirement making tape happy again.

**Comment by nathanhleung** [comment]
Thanks for the pull request and sorry for not getting back to you earlier - will take a look at the pull!

**Comment by nathanhleung** [comment]
Merged
