### ISSUE TITLE
npx install-peerdeps npm-linked-package fails

### ISSUE THREAD

**Issue by AquiGorka** [nathanhleung/install-peerdeps#42]
Hello there, I ran into a problem when trying to install `peerDependencies` for a package that is not yet published to the `npm` registry and that I `npm link`ed locally.

Got the following error: `ERR That package doesn't exist. Did you mean to specify a custom registry?`

Is there a flag I could use?

Thanks!

**Comment by nathanhleung** [comment]
The current behavior of this tool is that it reads peer dependencies of the specified package from the online NPM registry (or the registry specified by `--registry`) when downloading.

Unfortunately there's no flag to do what you want yet - you could try hosting your packages on a local private registry for now (see https://github.com/verdaccio/verdaccio) or just manually install your peer dependencies.

I'll keep this issue open though just so I know that this something to work on. Thanks for bringing this up.

**Comment by AquiGorka** [comment]
Thank you. Yeah, I manually installed the deps but it would be far easier if this could be automated - and obviously, if you are installing deps that means you don't have them locally, which means you can't look at their `package.json`s right away... so, thanks again for giving this an opportunity even if only by leaving the issue open.

**Comment by nathanhleung** [comment]
Hi, I'm going to close this issue in favor of #42 but will add the linking use case to the issue title in description. Thanks again for your report!
