### ISSUE TITLE
Custom registry not working?

### ISSUE THREAD

**Issue by yifanchen** [nathanhleung/install-peerdeps#48]
Hi there, 

I tried to install a package from a custom registry, it failed and said package can't be found on npmjs.org, which is not the registry where I commanded it to be.

Any idea what's going on? 

![image](https://user-images.githubusercontent.com/2340896/63080073-b972db80-bf72-11e9-890a-1cc3b4218132.png)

**Comment by yifanchen** [comment]
Additionally, what's the correct command format when I want to install a specific package from a custom registry? I tried a few times, didn't work out right.

![image](https://user-images.githubusercontent.com/2340896/63080232-2c7c5200-bf73-11e9-9696-33f7c9738154.png)

**Comment by AndreGeng** [comment]
Actually the registry option is not used when run "npm install" command, I have created a pr for this. [#48](https://github.com/nathanhleung/install-peerdeps/issues/48)

**Comment by nathanhleung** [comment]
Fixed by #49
