### ISSUE TITLE
[FR] Install peerdeps from local package

### ISSUE THREAD

**Issue by sarpik** [nathanhleung/install-peerdeps#62]
Don't know if this isn't already possible, but I'd like to be able to install peerdeps globally from a local package.

I have a local package ([eslint-config-sarpik](https://github.com/sarpik/eslint-config-sarpik)) which I have installed globally (not via linking (should I just use linking?)).

Sometimes I add some peerDependencies & I'd like to be able to install them myself globally prior to publishing.

Being able to do something like `npx install-peerdeps --global --yarn ./` would be awesome.

See also https://github.com/nathanhleung/install-peerdeps/pull/51 for locally linked packages.

**Comment by ljharb** [comment]
No eslint things should be installed globally; eslint v6 forces local installs more aggressively anyways.

**Comment by ljharb** [comment]
Global things aren’t requireable, so they*cant* satisfy peer dep requirements anyways.

**Comment by sarpik** [comment]
> No eslint things should be installed globally; eslint v6 forces local installs more aggressively anyways.

Yeah I've tried to get everything working with eslint `6.x` but wasted wayyy too much time and it didn't. Went back to `5.x` and it's awesome now.


> Global things aren’t requireable, so they_cant_ satisfy peer dep requirements anyways.

Don't understand this, could you elaborate?

**Comment by ljharb** [comment]
Yes. You can’t `require()` global packages, only run them on the command line. Peer deps are for things your package requires, in its code. Global packages this only make sense when they have no peer deps, which aces out any eslint things.

**Comment by sarpik** [comment]
I mean installing the peerDeps before publishing lets me test eslint out from the command line to make sure it's working fine, so the globally installed peerDeps do make a difference (I suppose?).

**Comment by ljharb** [comment]
I’m not sure what you mean. If you want to test a shared config before publishing, you’d npm link it, and each of its peer deps, into another project (or, install it from git in the other project).

**Comment by sarpik** [comment]
I'm trying to test a shared config, and I install the dependencies globally.

Doesn't matter though - I figured I'll just use `yarn link`.
Thank you for your time & help:)
