### ISSUE TITLE
Quote packages name, when calling npm

### ISSUE THREAD

**Issue by zdm** [nathanhleung/install-peerdeps#64]
Hi, you need to quote packages names, when you calling package manager.
For example, if peer deps is specified like ```"package": ">=1.2.3"```
then you will call npm to install deps like:
```npm i package@>=1.2.3```,  that produces stdout redirect to the file ```=1.2.3```

**Comment by nathanhleung** [comment]
#126 breaks the package, so I reverted it. Reopening this.

**Comment by zdm** [comment]
Seems, that this is not already actial with the npm 8.
