### ISSUE TITLE
Automatic proxy detection ignores NO_PROXY

### ISSUE THREAD

**Issue by erhhung** [nathanhleung/install-peerdeps#72]
While automatic detection of HTTP/S proxy server from standard environment variables is nice, the current implementation is ignoring hosts listed in the NO_PROXY environment variable. This issue manifests when using a private registry specified using the `--registry` option.

Once I removed my standard set of proxy environment variables, `install-peerdeps` runs fine.

I would consider using the [proxy-from-env](https://github.com/Rob--W/proxy-from-env) package to make this determination easier, and still allow override using the `--proxy` option.

**Comment by amclin** [comment]
There's no way this can be done consistently for all proxy configurations. My corporate environemnt has a configuration where the environment variable settings work for `curl` but fail for `npm` but work for some NPM packages that use HTTP libraries, but not others. It's a total crapshoot and every proxy setup is different.

Better to remove this custom API-handling entirely and use the native commands provided by the package manager. Then there's no need to be messing with package-specific proxy configurations.
